In [1]:
# Import dependencies
import pandas as pd
import geopandas
import geojson

In [2]:
# Create dataframe with data for map
file_path = "./Resources/processed_PLACES_COPD.csv"
predicted_df = pd.read_csv(file_path)
predicted_df

,State_County,State,County,Levels_Smokers,Levels_COPD
0,"Cass, Iowa",Iowa,Cass,19.3,8.3
1,"Monona, Iowa",Iowa,Monona,18.5,8.3
2,"Dillingham, Alaska",Alaska,Dillingham,31.1,8.9
3,"Custer, Colorado",Colorado,Custer,13.8,7.5
4,"Ketchikan Gateway, Alaska",Alaska,Ketchikan Gateway,19.4,6.6
...,...,...,...,...,...
3117,"Sauk, Wisconsin",Wisconsin,Sauk,16.8,6.5
3118,"Brown, Wisconsin",Wisconsin,Brown,15.1,5.5
3119,"Webster, West Virginia",West Virginia,Webster,26.8,15.3
3120,"Winnebago, Wisconsin",Wisconsin,Winnebago,17.1,5.8
3121,"Waukesha, Wisconsin",Wisconsin,Waukesha,12.6,4.7

In [3]:
predicted_df = predicted_df.drop(["State_County"], axis=1)
predicted_df

              State             County  Levels_Smokers  Levels_COPD
0              Iowa               Cass            19.3          8.3
1              Iowa             Monona            18.5          8.3
2            Alaska         Dillingham            31.1          8.9
3          Colorado             Custer            13.8          7.5
4            Alaska  Ketchikan Gateway            19.4          6.6
...             ...                ...             ...          ...
3117      Wisconsin               Sauk            16.8          6.5
3118      Wisconsin              Brown            15.1          5.5
3119  West Virginia            Webster            26.8         15.3
3120      Wisconsin          Winnebago            17.1          5.8
3121      Wisconsin           Waukesha            12.6          4.7

[3122 rows x 4 columns]

In [4]:
# Upload geoJSON file for map
file_path = "../COPD_Mapping/static/data/county.geojson"
county_df = geopandas.read_file(file_path)
county_df.head(25)

,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,02,013,01419964,02013,Aleutians East,Aleutians East Borough,04,H1,G4020,None,None,None,A,1.808315e+10,2.079221e+10,+55.2437223,-161.9507485,"MULTIPOLYGON (((-162.63769 54.80112, -162.6411..."
1,02,016,01419965,02016,Aleutians West,Aleutians West Census Area,05,H5,G4020,None,None,None,S,1.137076e+10,2.519064e+10,+51.9594469,+178.3388130,"MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28,107,00695776,28107,Panola,Panola County,06,H1,G4020,None,None,None,A,1.774516e+09,5.176705e+07,+34.3652052,-089.9630654,"POLYGON ((-90.13476 34.22603, -90.13476 34.226..."
3,28,101,00695773,28101,Newton,Newton County,06,H1,G4020,None,None,None,A,1.497283e+09,3.879399e+06,+32.4019702,-089.1184115,"POLYGON ((-89.13497 32.57697, -89.13466 32.576..."
4,28,027,00695738,28027,Coahoma,Coahoma County,06,H1,G4020,None,17260,None,A,1.430818e+09,7.953947e+07,+34.2286699,-090.6031650,"POLYGON ((-90.59063 33.98690, -90.59473 33.986..."
5,22,065,00558088,22065,Madison,Madison Parish,15,H1,G4020,None,45260,None,A,1.617283e+09,6.853867e+07,+32.3658243,-091.2407290,"MULTIPOLYGON (((-91.03511 32.12035, -91.03621 ..."
6,51,540,01789068,51540,Charlottesville,Charlottesville city,25,C7,G4020,None,16820,None,F,2.651736e+07,5.297400e+04,+38.0376579,-078.4853806,"POLYGON ((-78.47071 38.04872, -78.47033 38.048..."
7,51,510,01498415,51510,Alexandria,Alexandria city,25,C7,G4020,548,47900,47894,F,3.891973e+07,1.140371e+06,+38.8183429,-077.0820263,"POLYGON ((-77.06247 38.79496, -77.06267 38.795..."
8,51,530,01498417,51530,Buena Vista,Buena Vista city,25,C7,G4020,None,None,None,F,1.736224e+07,2.238550e+05,+37.7316634,-079.3563746,"POLYGON ((-79.36681 37.72722, -79.36686 37.727..."
9,51,600,01789070,51600,Fairfax,Fairfax city,25,C7,G4020,548,47900,47894,F,1.615946e+07,9.505400e+04,+38.8531833,-077.2990252,"POLYGON ((-77.31427 38.86700, -77.31414 38.867..."
10,48,113,01383842,48113,Dallas,Dallas County,06,H1,G4020,206,19100,19124,A,2.256603e+09,9.669635e+07,+32.7669866,-096.7784238,"POLYGON ((-96.52999 32.54528, -96.53330 32.545..."
11,48,227,01383899,48227,Howard,Howard County,06,H1,G4020,None,13700,None,A,2.333038e+09,8.841951e+06,+32.3035834,-101.4385304,"POLYGON ((-101.17470 32.49329, -101.17470 32.4..."
12,48,155,01383863,48155,Foard,Foard County,06,H1,G4020,None,None,None,A,1.824379e+09,8.514811e+06,+33.9804040,-099.7774272,"POLYGON ((-99.59622 33.78740, -99.59627 33.787..."
13,48,153,01383862,48153,Floyd,Floyd County,06,H1,G4020,None,None,None,A,2.569637e+09,9.837400e+05,+34.0737305,-101.3032742,"POLYGON ((-101.56453 34.05969, -101.56456 34.0..."
14,48,043,01383807,48043,Brewster,Brewster County,06,H1,G4020,None,None,None,A,1.601580e+10,2.206400e+07,+29.8089965,-103.2524579,"POLYGON ((-103.32538 30.58608, -103.32531 30.5..."
15,48,159,01383865,48159,Franklin,Franklin County,06,H1,G4020,None,None,None,A,7.365690e+08,2.687609e+07,+33.1758457,-095.2190662,"POLYGON ((-95.30845 33.02455, -95.30844 33.029..."
16,48,231,01383901,48231,Hunt,Hunt County,06,H1,G4020,206,19100,19124,A,2.176414e+09,1.080148e+08,+33.1234378,-096.0838072,"POLYGON ((-95.86178 33.21933, -95.86178 33.219..."
17,48,351,01383961,48351,Newton,Newton County,06,H1,G4020,None,None,None,A,2.418212e+09,1.567210e+07,+30.7867182,-093.7392500,"POLYGON ((-93.55074 30.92123, -93.55078 30.921..."
18,48,427,01383999,48427,Starr,Starr County,06,H1,G4020,None,40100,None,A,3.168019e+09,1.530228e+07,+26.5463354,-098.7158034,"POLYGON ((-98.85127 26.78533, -98.84910 26.785..."
19,48,271,01383921,48271,Kinney,Kinney County,06,H1,G4020,None,None,None,A,3.522526e+09,1.312508e+07,+29.3470865,-100.4177003,"POLYGON ((-100.11224 29.46769, -100.11225 29.4..."
20,48,087,01383829,48087,Collingsworth,Collingsworth County,06,H1,G4020,None,None,None,A,2.378751e+09,2.279238e+06,+34.9633577,-100.2721351,"POLYGON ((-100.53965 34.99391, -100.53962 34.9..."
21,48,451,01384011,48451,Tom Green,Tom Green County,06,H1,G4020,None,41660,None,A,3.941890e+09,4.810479e+07,+31.4015829,-100.4613549,"POLYGON ((-100.44159 31.69307, -100.44153 31.6..."
22,48,083,01383827,48083,Coleman,Coleman County,06,H1,G4020,None,None,None,A,3.268424e+09,5.047227e+07,+31.9142052,-099.3466224,"POLYGON ((-99.71619 31.89906, -99.71618 31.899..."
23,48,039,01383805,48039,Brazoria,Brazoria County,06,H1,G4020,288,26420,None,A,3.516430e+09,6.497927e+08,+29.1678175,-095.4346470,"POLYGON ((-95.05714 29.20088, -95.05709 29.200..."
24,48,289,01383930,48289,Leon,Leon County,06,H1,G4020,None,None,None,A,2.779447e+09,1.934305e+07,+31.3004925,-095.9956219,"POLYGON ((-96.26059 31.07707, -96.26094 31.076..."

In [5]:
county_df.rename(columns = {'NAME10':'County'}, inplace = True)
county_df.head()

,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,County,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,02,013,01419964,02013,Aleutians East,Aleutians East Borough,04,H1,G4020,None,None,None,A,1.808315e+10,2.079221e+10,+55.2437223,-161.9507485,"MULTIPOLYGON (((-162.63769 54.80112, -162.6411..."
1,02,016,01419965,02016,Aleutians West,Aleutians West Census Area,05,H5,G4020,None,None,None,S,1.137076e+10,2.519064e+10,+51.9594469,+178.3388130,"MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28,107,00695776,28107,Panola,Panola County,06,H1,G4020,None,None,None,A,1.774516e+09,5.176705e+07,+34.3652052,-089.9630654,"POLYGON ((-90.13476 34.22603, -90.13476 34.226..."
3,28,101,00695773,28101,Newton,Newton County,06,H1,G4020,None,None,None,A,1.497283e+09,3.879399e+06,+32.4019702,-089.1184115,"POLYGON ((-89.13497 32.57697, -89.13466 32.576..."
4,28,027,00695738,28027,Coahoma,Coahoma County,06,H1,G4020,None,17260,None,A,1.430818e+09,7.953947e+07,+34.2286699,-090.6031650,"POLYGON ((-90.59063 33.98690, -90.59473 33.986..."

In [6]:
# Look at what numbers are used for State FIPS identifiers
county_df.STATEFP10.unique().tolist()
# It appears they are not simply 1-50. Need a key to translate these to the appropriate State name

['02',
 '28',
 '22',
 '51',
 '48',
 '34',
 '23',
 '50',
 '56',
 '29',
 '17',
 '06',
 '49',
 '37',
 '42',
 '39',
 '36',
 '04',
 '35',
 '24',
 '44',
 '41',
 '53',
 '72',
 '55',
 '38',
 '32',
 '13',
 '05',
 '20',
 '31',
 '40',
 '54',
 '26',
 '08',
 '10',
 '30',
 '09',
 '25',
 '21',
 '12',
 '11',
 '16',
 '45',
 '15',
 '01',
 '33',
 '46',
 '47',
 '18',
 '19',
 '27']

In [7]:
# Remove leading zeroes from STATEFP10
county_df['STATEFP10'] = county_df['STATEFP10'].str.lstrip('0')
county_df.head()

,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,County,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,2,013,01419964,02013,Aleutians East,Aleutians East Borough,04,H1,G4020,None,None,None,A,1.808315e+10,2.079221e+10,+55.2437223,-161.9507485,"MULTIPOLYGON (((-162.63769 54.80112, -162.6411..."
1,2,016,01419965,02016,Aleutians West,Aleutians West Census Area,05,H5,G4020,None,None,None,S,1.137076e+10,2.519064e+10,+51.9594469,+178.3388130,"MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28,107,00695776,28107,Panola,Panola County,06,H1,G4020,None,None,None,A,1.774516e+09,5.176705e+07,+34.3652052,-089.9630654,"POLYGON ((-90.13476 34.22603, -90.13476 34.226..."
3,28,101,00695773,28101,Newton,Newton County,06,H1,G4020,None,None,None,A,1.497283e+09,3.879399e+06,+32.4019702,-089.1184115,"POLYGON ((-89.13497 32.57697, -89.13466 32.576..."
4,28,027,00695738,28027,Coahoma,Coahoma County,06,H1,G4020,None,17260,None,A,1.430818e+09,7.953947e+07,+34.2286699,-090.6031650,"POLYGON ((-90.59063 33.98690, -90.59473 33.986..."

In [8]:
# Check datatypes
county_df.dtypes

STATEFP10       object
COUNTYFP10      object
COUNTYNS10      object
GEOID10         object
County          object
NAMELSAD10      object
LSAD10          object
CLASSFP10       object
MTFCC10         object
CSAFP10         object
CBSAFP10        object
METDIVFP10      object
FUNCSTAT10      object
ALAND10        float64
AWATER10       float64
INTPTLAT10      object
INTPTLON10      object
geometry      geometry
dtype: object

In [9]:
# Get State FIPS key chart and make it a dataframe
file_path = "https://gist.githubusercontent.com/dantonnoriega/bf1acd2290e15b91e6710b6fd3be0a53/raw/11d15233327c8080c9646c7e1f23052659db251d/us-state-ansi-fips.csv"
fips_df = pd.read_csv(file_path)
fips_df.head()

       stname   st  stusps
0     Alabama    1      AL
1      Alaska    2      AK
2     Arizona    4      AZ
3    Arkansas    5      AR
4  California    6      CA

In [10]:
fips_df.columns = ["State", "STATEFP10", "State_Abbrv"]
fips_df.head()

        State  STATEFP10 State_Abbrv
0     Alabama          1          AL
1      Alaska          2          AK
2     Arizona          4          AZ
3    Arkansas          5          AR
4  California          6          CA

In [11]:
fips_df["STATEFP10"] = fips_df["STATEFP10"].astype('str')

In [12]:
fips_df.dtypes

State          object
STATEFP10      object
State_Abbrv    object
dtype: object

In [13]:
# Merge dataframes
datamap_df = fips_df.merge(county_df, on="STATEFP10")
datamap_df.head(5)

,State,STATEFP10,State_Abbrv,COUNTYFP10,COUNTYNS10,GEOID10,County,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,Alabama,1,AL,005,00161528,01005,Barbour,Barbour County,06,H1,G4020,None,21640,None,A,2.291819e+09,50864716.0,+31.8706701,-085.4054562,"POLYGON ((-85.62028 31.94550, -85.61987 31.945..."
1,Alabama,1,AL,027,00161539,01027,Clay,Clay County,06,H1,G4020,None,None,None,A,1.564252e+09,5284628.0,+33.2678085,-085.8620510,"POLYGON ((-85.97880 33.32749, -85.97854 33.332..."
2,Alabama,1,AL,091,00161572,01091,Marengo,Marengo County,06,H1,G4020,None,None,None,A,2.530112e+09,14994547.0,+32.2475911,-087.7910910,"POLYGON ((-87.71055 32.48078, -87.71054 32.480..."
3,Alabama,1,AL,069,00161560,01069,Houston,Houston County,06,H1,G4020,222,20020,None,A,1.501738e+09,4739984.0,+31.1581928,-085.2963976,"POLYGON ((-85.16205 31.30787, -85.15996 31.307..."
4,Alabama,1,AL,019,00161535,01019,Cherokee,Cherokee County,06,H1,G4020,None,None,None,A,1.434076e+09,119858898.0,+34.0695153,-085.6542417,"POLYGON ((-85.57299 33.95853, -85.57300 33.958..."

In [14]:
# Merge dataframes
datamap_df = predicted_df.merge(datamap_df, on=["State", "County"])

In [15]:
# View the dataframe
pd.set_option('display.max_columns', 50)
datamap_df.head(5)

,State,County,Levels_Smokers,Levels_COPD,STATEFP10,State_Abbrv,COUNTYFP10,COUNTYNS10,GEOID10,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,Iowa,Cass,19.3,8.3,19,IA,029,00465204,19029,Cass County,06,H1,G4020,None,None,None,A,1.461451e+09,1.758815e+06,+41.3338235,-094.9333023,"POLYGON ((-94.81495 41.15839, -94.81506 41.158..."
1,Iowa,Monona,18.5,8.3,19,IA,133,00465255,19133,Monona County,06,H1,G4020,None,None,None,A,1.797638e+09,1.259188e+07,+42.0494317,-095.9565661,"POLYGON ((-95.78944 41.86330, -95.79007 41.863..."
2,Alaska,Dillingham,31.1,8.9,2,AK,070,01419968,02070,Dillingham Census Area,05,H5,G4020,None,None,None,S,4.809291e+10,6.077224e+09,+59.8248160,-158.6022333,"MULTIPOLYGON (((-159.86345 58.57869, -159.8681..."
3,Colorado,Custer,13.8,7.5,8,CO,027,00198129,08027,Custer County,06,H1,G4020,None,None,None,A,1.913031e+09,3.364771e+06,+38.1019939,-105.3735148,"POLYGON ((-105.56031 37.95189, -105.56235 37.9..."
4,Alaska,Ketchikan Gateway,19.4,6.6,2,AK,130,01419973,02130,Ketchikan Gateway Borough,04,H1,G4020,None,28540,None,A,1.258323e+10,4.649414e+09,+55.4499378,-131.1066847,"POLYGON ((-131.92856 55.26062, -131.93524 55.2..."

In [16]:
# Remove unneeded data
datamap_df = datamap_df.drop(["State_Abbrv", "NAMELSAD10", "CSAFP10", "CBSAFP10", "METDIVFP10"], axis=1)
datamap_df.head()

,State,County,Levels_Smokers,Levels_COPD,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,LSAD10,CLASSFP10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,Iowa,Cass,19.3,8.3,19,029,00465204,19029,06,H1,G4020,A,1.461451e+09,1.758815e+06,+41.3338235,-094.9333023,"POLYGON ((-94.81495 41.15839, -94.81506 41.158..."
1,Iowa,Monona,18.5,8.3,19,133,00465255,19133,06,H1,G4020,A,1.797638e+09,1.259188e+07,+42.0494317,-095.9565661,"POLYGON ((-95.78944 41.86330, -95.79007 41.863..."
2,Alaska,Dillingham,31.1,8.9,2,070,01419968,02070,05,H5,G4020,S,4.809291e+10,6.077224e+09,+59.8248160,-158.6022333,"MULTIPOLYGON (((-159.86345 58.57869, -159.8681..."
3,Colorado,Custer,13.8,7.5,8,027,00198129,08027,06,H1,G4020,A,1.913031e+09,3.364771e+06,+38.1019939,-105.3735148,"POLYGON ((-105.56031 37.95189, -105.56235 37.9..."
4,Alaska,Ketchikan Gateway,19.4,6.6,2,130,01419973,02130,04,H1,G4020,A,1.258323e+10,4.649414e+09,+55.4499378,-131.1066847,"POLYGON ((-131.92856 55.26062, -131.93524 55.2..."

In [17]:
# Export file path
file_path = '../COPD_Mapping/static/data/data_map.geojson.zip'

In [18]:
datamap_df.to_file(file_path, index=False, driver="GeoJSON")

AttributeError: 'DataFrame' object has no attribute 'to_file'

In [ ]:
# geo_json = to_geojson(df=datamap_df, lat='lat', lon='long',
#                  properties=['name','marker-symbol','marker-color'])
# print(geo_json)

In [ ]:
# json_output = r'../COPD_Mapping/static/data/data_map.geojson.zip'
# output = datamap_df.to_json(json_output, indent=1, orient="records", default_handler=str)