In [1]:
import pandas as pd
import geopandas

In [2]:
# Create dataframe with data for map
file_path = "./Resources/processed_PLACES_COPD.csv"
predicted_df = pd.read_csv(file_path)
predicted_df

,State_County,State,County,Levels_Smokers,Levels_COPD
0,"Cass, Iowa",Iowa,Cass,19.3,8.3
1,"Monona, Iowa",Iowa,Monona,18.5,8.3
2,"Dillingham, Alaska",Alaska,Dillingham,31.1,8.9
3,"Custer, Colorado",Colorado,Custer,13.8,7.5
4,"Ketchikan Gateway, Alaska",Alaska,Ketchikan Gateway,19.4,6.6
...,...,...,...,...,...
3117,"Sauk, Wisconsin",Wisconsin,Sauk,16.8,6.5
3118,"Brown, Wisconsin",Wisconsin,Brown,15.1,5.5
3119,"Webster, West Virginia",West Virginia,Webster,26.8,15.3
3120,"Winnebago, Wisconsin",Wisconsin,Winnebago,17.1,5.8
3121,"Waukesha, Wisconsin",Wisconsin,Waukesha,12.6,4.7

In [4]:
# Upload geoJSON file for map
file_path = "../COPD_Mapping/static/data/county.geojson"
county_df = geopandas.read_file(file_path)
county_df

,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,CBSAFP10,METDIVFP10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,02,013,01419964,02013,Aleutians East,Aleutians East Borough,04,H1,G4020,None,None,None,A,1.808315e+10,2.079221e+10,+55.2437223,-161.9507485,"MULTIPOLYGON (((-162.63769 54.80112, -162.6411..."
1,02,016,01419965,02016,Aleutians West,Aleutians West Census Area,05,H5,G4020,None,None,None,S,1.137076e+10,2.519064e+10,+51.9594469,+178.3388130,"MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28,107,00695776,28107,Panola,Panola County,06,H1,G4020,None,None,None,A,1.774516e+09,5.176705e+07,+34.3652052,-089.9630654,"POLYGON ((-90.13476 34.22603, -90.13476 34.226..."
3,28,101,00695773,28101,Newton,Newton County,06,H1,G4020,None,None,None,A,1.497283e+09,3.879399e+06,+32.4019702,-089.1184115,"POLYGON ((-89.13497 32.57697, -89.13466 32.576..."
4,28,027,00695738,28027,Coahoma,Coahoma County,06,H1,G4020,None,17260,None,A,1.430818e+09,7.953947e+07,+34.2286699,-090.6031650,"POLYGON ((-90.59063 33.98690, -90.59473 33.986..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,37,077,01008556,37077,Granville,Granville County,06,H1,G4020,None,None,None,A,1.376759e+09,1.276561e+07,+36.2998840,-078.6576338,"POLYGON ((-78.80329 36.17716, -78.80324 36.179..."
3217,37,111,01025836,37111,McDowell,McDowell County,06,H1,G4020,None,None,None,A,1.141169e+09,1.395676e+07,+35.6822317,-082.0480292,"POLYGON ((-81.86107 35.69329, -81.86077 35.692..."
3218,27,021,00659456,27021,Cass,Cass County,06,H1,G4020,None,14660,None,A,5.235770e+09,1.016740e+09,+46.9514271,-094.3337731,"POLYGON ((-94.65939 46.89070, -94.65936 46.892..."
3219,27,057,00659474,27057,Hubbard,Hubbard County,06,H1,G4020,None,None,None,A,2.397486e+09,1.913607e+08,+47.0955506,-094.9132898,"POLYGON ((-95.16917 47.15252, -95.16917 47.155..."
3220,27,169,00659529,27169,Winona,Winona County,06,H1,G4020,None,49100,None,A,1.621865e+09,3.982540e+07,+43.9822682,-091.7767076,"POLYGON ((-92.07904 43.95532, -92.07904 43.957..."

In [ ]:
merged_df = predicted_df

In [ ]:
# Export the dataframe to csv
merged_df.to_csv('../COPD_Mapping/static/data/data_map.csv', index=False)